# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'GourmetRecipes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'SDWebImage'
pod 'AFNetworking'
pod 'YYModel'
pod 'Masonry'
pod 'MJRefresh'
pod 'MBProgressHUD'

end
